# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6c9128ed203a5ffc46262f88b713b7e8409fb65e386843ef1573e8139315d3421ea6f37574e1ee715825265b8d5397441c0739867007bb4790f4c43ee4218af

test:
  secret_key_base: 320789c98e8c706b471b7527f7be74feb0b1c4cc3b1c70568b0fa99d6fb38e9d573d89259b2863c7a35c921698a9b42c57a4d3dc85e4f39417fe56d5b402faef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
